Now that OpenVAS adds the right inflection we need to use it
Or we get:

```
NameError: uninitialized constant CleanOpenVASSettings
Did you mean?  CleanOpenvasSettings
```